// <auto-generated />
using System;
using Laszlo_Sebastian_Proiect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Laszlo_Sebastian_Proiect.Migrations
{
    [DbContext(typeof(Laszlo_Sebastian_ProiectContext))]
    [Migration("20240117200241_Styles")]
    partial class Styles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Laszlo_Sebastian_Proiect.Models.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("Laszlo_Sebastian_Proiect.Models.Style", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StyleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Style");
                });

            modelBuilder.Entity("Laszlo_Sebastian_Proiect.Models.Tattoo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("AgeConfirmation")
                        .HasColumnType("bit");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StyleID")
                        .HasColumnType("int");

                    b.Property<int?>("TattooArtistID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationID");

                    b.HasIndex("StyleID");

                    b.HasIndex("TattooArtistID");

                    b.ToTable("Tattoo");
                });

            modelBuilder.Entity("Laszlo_Sebastian_Proiect.Models.TattooArtist", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationID")
                        .HasColumnType("int");

                    b.Property<int?>("StyleID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("LocationID");

                    b.HasIndex("StyleID");

                    b.ToTable("TattooArtist");
                });

            modelBuilder.Entity("Laszlo_Sebastian_Proiect.Models.Tattoo", b =>
                {
                    b.HasOne("Laszlo_Sebastian_Proiect.Models.Location", "Location")
                        .WithMany("Tattoos")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Laszlo_Sebastian_Proiect.Models.Style", "Style")
                        .WithMany("Tattoos")
                        .HasForeignKey("StyleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Laszlo_Sebastian_Proiect.Models.TattooArtist", "TattooArtist")
                        .WithMany("Tattoos")
                        .HasForeignKey("TattooArtistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Style");

                    b.Navigation("TattooArtist");
                });

            modelBuilder.Entity("Laszlo_Sebastian_Proiect.Models.TattooArtist", b =>
                {
                    b.HasOne("Laszlo_Sebastian_Proiect.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID");

                    b.HasOne("Laszlo_Sebastian_Proiect.Models.Style", "Style")
                        .WithMany("TattooArtists")
                        .HasForeignKey("StyleID");

                    b.Navigation("Location");

                    b.Navigation("Style");
                });

            modelBuilder.Entity("Laszlo_Sebastian_Proiect.Models.Location", b =>
                {
                    b.Navigation("Tattoos");
                });

            modelBuilder.Entity("Laszlo_Sebastian_Proiect.Models.Style", b =>
                {
                    b.Navigation("TattooArtists");

                    b.Navigation("Tattoos");
                });

            modelBuilder.Entity("Laszlo_Sebastian_Proiect.Models.TattooArtist", b =>
                {
                    b.Navigation("Tattoos");
                });
#pragma warning restore 612, 618
        }
    }
}
